source 'https://rubygems.org'

ruby '2.1.2'

gem 'rails', '~> 4.1.1'

gem 'faker'

gem 'bcrypt'

gem 'puma'

gem 'devise', github: 'plataformatec/devise'
gem 'cancancan'

gem 'rabl'
gem 'oj'

gem 'mongoid', github: 'mongoid/mongoid'

gem 'mongoid-paperclip'
gem 'mongoid-history'

gem 'elasticsearch-model'
gem 'elasticsearch-rails'

gem 'will_paginate'
gem 'will_paginate_mongoid'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'annotate'
  gem 'bullet'
  gem 'flay'
  gem 'hirb'
  gem 'lol_dba'
  gem 'meta_request'

  gem 'quiet_assets'
  gem 'rack-mini-profiler'
  gem 'rails_best_practices'

  #pry package
  gem 'pry'
  gem 'pry-remote'
  gem 'pry-doc'
  gem 'pry-rails'
  gem 'pry-stack_explorer'
  gem 'pry-nav'
  gem 'rb-readline', require: false

  #livereload
  gem 'guard'
  gem 'guard-zeus'
  gem 'guard-livereload'
  gem 'rack-livereload'

  gem 'rb-fsevent', require: false
  gem 'zeus'
  gem 'spring'
end
